Created entities
olehvolynets/bookstore pull request #13
Opened 2020-02-12 20:24 UTC by sagg0t

2020-02-24 15:54 UTC, Svatok requested changes
Pass to command only session[:order_id] instead of all session

2020-02-24 15:54 UTC, Svatok commented on app/commands/apply_coupon.rb
> +    coupon = Coupon.where(code: form.code).first
find_by

2020-02-24 15:54 UTC, Svatok commented on app/commands/apply_coupon.rb
> +    Order.find(session[:order_id]).update(coupon: coupon)
Please create helper method for `Order.find(session[:order_id])`

2020-02-24 15:54 UTC, Svatok commented on app/commands/bind_order_to_user.rb
> +    session[:order_id] = nil unless order.user_id == user.id
Update session only in controllers

2020-02-24 15:54 UTC, Svatok commented on app/commands/order_item/change_quantity.rb
> +    @quantity = (params[:quantity] || params.dig(:order_item, :quantity)).to_i
Please rename param

2020-02-24 15:54 UTC, Svatok commented on app/commands/order_item/change_quantity.rb
> +  def owner_verified?
```ruby
def item
  @item ||= current_order.items.find_by(id: params[:id])
end
```

2020-02-24 15:54 UTC, Svatok commented on app/commands/order_item/change_quantity.rb
> +    return broadcast(:invalid) unless owner_verified?
`unless item`

2020-02-24 15:54 UTC, Svatok commented on app/commands/order_item/change_quantity.rb
> +    new_quantity = quantity < 1 ? 1 : limited_quantity
Please rename to 'max_quantity'

2020-02-24 15:54 UTC, Svatok commented on app/commands/order_item/change_quantity.rb
> +    new_quantity = quantity < 1 ? 1 : limited_quantity
Please use `positive?`

2020-02-24 15:54 UTC, Svatok commented on app/commands/update_order.rb
> +    return add_item if params[:book_id]
Please rename params

2020-02-24 15:54 UTC, Svatok commented on app/commands/update_order.rb
> +  def order_from_user
Please remove this method

2020-02-25 16:18 UTC, Svatok commented on app/controllers/carts_controller.rb
> +        redirect_to request.url
https://api.rubyonrails.org/classes/ActionController/Redirecting.html

2020-02-25 16:18 UTC, Svatok commented on app/forms/coupon_form.rb
> +    coupon_exists?
Please divide this validation for two validations.

2020-02-25 16:18 UTC, Svatok commented on app/forms/coupon_form.rb
> +    return if Coupon.where(code: code).present?
`.exists?` instead of `present?`
https://andreigridnev.com/blog/2016-04-17-empty-blank-any-exists-methods-of-ruby-on-rails-activerecord/

2020-02-25 16:18 UTC, Svatok commented on app/models/book.rb
> +  has_many :order_items, dependent: :nullify
Please use soft delete for books
https://github.com/jhawthorn/discard

2020-02-25 16:18 UTC, Svatok commented on app/models/order_item.rb
> +  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
Please check do we use this?

2020-02-25 16:18 UTC, Svatok commented on app/presenters/carts_presenter.rb
> +    order&.order_items&.size || 0
items.count

2020-02-25 16:18 UTC, Svatok commented on app/presenters/carts_presenter.rb
> +    order.order_items.includes(:book)
@items ||= order.order_items.includes(:book)

2020-02-25 16:18 UTC, Svatok commented on app/presenters/carts_presenter.rb
> +  def items_size
Please move this to separate presenter

2020-02-25 16:18 UTC, Svatok commented on app/presenters/carts_presenter.rb
> +    return coupon.discount_value if coupon.discount_type == 'amount'
coupon.amount?

2020-02-25 16:18 UTC, Svatok commented on app/workers/cart_cleanup_worker.rb
> +    Order.cart.where('created_at < ?', 3.days.ago).destroy_all
https://github.com/moove-it/sidekiq-scheduler

2020-02-25 16:18 UTC, Svatok commented on config/initializers/sidekiq.rb
> +
https://github.com/mperham/sidekiq/wiki/Testing

2020-02-27 14:13 UTC, Svatok reviewed
Please remove `!` in all `let` in tests where this symbol is unnecessary .
Please add tests for broadcasts checking
Please stub `current_order` instead of session stub. And create one test for checking current_order without stubbing.

2020-02-27 14:13 UTC, Svatok commented on app/commands/bind_order_to_user.rb
> +    return unless order
I think order never be nil here

2020-02-27 14:13 UTC, Svatok commented on app/commands/order_item/change_quantity.rb
> +    @order = order
Can we move `@order` to initializer in OrderBaseCommand?

2020-02-27 14:13 UTC, Svatok commented on app/controllers/concerns/with_cart.rb
> +    @items_count ||= OrderItem.where(order_id: session[:order_id]).count
`current_order.order_items`

2020-02-27 14:13 UTC, Svatok commented on app/forms/coupon_form.rb
> +  validate :coupon_validations
please create two separate validations

2020-02-27 14:13 UTC, Svatok commented on app/models/book.rb
> +  # rubocop:disable Rails/HasManyOrHasOneDependent
Please fix this

2020-02-27 14:13 UTC, Svatok commented on app/models/coupon.rb
> +  # rubocop:disable Rails/HasManyOrHasOneDependent
Please fix this

2020-02-27 14:13 UTC, Svatok commented on app/presenters/carts_presenter.rb
> +    items.reduce(0) { |total, item| total + item.total }
`items.sum(&:total)`

2020-02-27 14:13 UTC, Svatok commented on spec/commands/apply_coupon_spec.rb
> +  let!(:order) { create(:order) }
`!` is unnecessary here

2020-02-27 14:13 UTC, Svatok commented on spec/commands/apply_coupon_spec.rb
> +      expect { service_call }.to broadcast(:invalid, CouponForm)
Please check that `order.reload.coupon` is not changed

2020-02-27 14:13 UTC, Svatok commented on spec/commands/apply_coupon_spec.rb
> +      expect { service_call }.to broadcast(:invalid, CouponForm)
Please check that `order.reload.coupon` is not changed

2020-02-27 14:13 UTC, Svatok commented on spec/commands/bind_order_to_user_spec.rb
> +  let!(:user) { create(:user) }
Remove `!`

2020-02-27 14:13 UTC, Svatok commented on spec/commands/bind_order_to_user_spec.rb
> +    let!(:order) { create(:order) }
Remove `!`

2020-02-27 14:13 UTC, Svatok commented on spec/commands/bind_order_to_user_spec.rb
> +describe BindOrderToUser do
Please check broadcasts for all tests

2020-02-27 14:13 UTC, Svatok commented on spec/commands/bind_order_to_user_spec.rb
> +    let!(:order) { create(:order, user: another_user) }
Remove `!`

2020-02-27 14:13 UTC, Svatok commented on spec/commands/order_item/create_spec.rb
> +      expect { service_call }.to change(OrderItem, :count).by(1).and change { order.reload.order_items.size }.by(1)
Please use `from().to()` instead of `by()`

2020-02-27 14:13 UTC, Svatok commented on spec/factories/order.rb
> +      items { 1 }
Please rename to `items_count`

2020-02-27 14:13 UTC, Svatok commented on spec/features/cart_page_spec.rb
> +      allow_any_instance_of(CartsController).to receive(:session).and_return(session)
Can we omit session stub? For example we can stub `current_order`

2020-02-27 15:05 UTC, sagg0t commented on app/controllers/concerns/with_cart.rb
> +    @items_count ||= OrderItem.where(order_id: session[:order_id]).count
This will trigger order fetch from db, that is not required on most of the pages.

2020-02-27 15:06 UTC, sagg0t commented on app/forms/coupon_form.rb
> +  validate :coupon_validations
They need to be executed sequentially and second one shouldn't be executed unless first passes. So separating is not the best option in my opinion

2020-02-27 16:11 UTC, Svatok approved these changes

2020-02-27 16:20 UTC, merged