Feature/catalog,  book page
olehvolynets/bookstore pull request #3
Opened 2019-10-17 15:02 UTC by olehvolynets

2019-11-11 10:53 UTC, dmbavykin requested changes

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/book_filter_query.rb
> +  def initialize(params = {}, relation = Book.includes(:category))
use `joins` for filtering

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/book_filter_query.rb
> +  def initialize(params = {}, relation = Book.includes(:category))
https://medium.com/@swapnilggourshete/rails-includes-vs-joins-9bf3a8ada00

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/book_filter_query.rb
> +  def initialize(params = {}, relation = Book.includes(:category))
```ruby
[16] pry(main)> puts Order.joins(:company).where(companies: { name: "test" }).to_sql
SELECT "orders".* FROM "orders" INNER JOIN "companies" ON "companies"."id" = "orders"."company_id" WHERE "companies"."name" = 'test'
=> nil
[17] pry(main)>
[18] pry(main)> puts Order.includes(:company).where(companies: { name: "test" }).to_sql
SELECT "orders"."id" AS t0_r0, "orders"."company_id" AS t0_r1, "orders"."po_number" AS t0_r2, "orders"."status" AS t0_r3, "orders"."tracking_number" AS t0_r4, "orders"."created_at" AS t0_r5, "orders"."updated_at" AS t0_r6, "orders"."ngc_id" AS t0_r7, "orders"."shipping_cost" AS t0_r8, "orders"."shipping_discount" AS t0_r9, "orders"."exported_at" AS t0_r10, "orders"."confirmation_sent_at" AS t0_r11, "orders"."shipped_sent_at" AS t0_r12, "orders"."shipped_at" AS t0_r13, "orders"."program_id" AS t0_r14, "orders"."custom_fields" AS t0_r15, "orders"."fulfillment_type" AS t0_r16, "companies"."id" AS t1_r0, "companies"."name" AS t1_r1, "companies"."url" AS t1_r2, "companies"."primary_contact_id" AS t1_r3, "companies"."created_at" AS t1_r4, "companies"."updated_at" AS t1_r5, "companies"."discount_percent" AS t1_r6, "companies"."non_profit" AS t1_r7, "companies"."non_profit_tax_number" AS t1_r8, "companies"."free_shipping" AS t1_r9, "companies"."internal" AS t1_r10 FROM "orders" LEFT OUTER JOIN "companies" ON "companies"."id" = "orders"."company_id" WHERE "companies"."name" = 'test'
=> nil
```

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/application_query.rb
> +    new(*args, &block).call
👍

2019-11-11 10:53 UTC, dmbavykin commented on app/models/books_material.rb
> +class BooksMaterial < ApplicationRecord
`BookMaterial`

2019-11-11 10:53 UTC, dmbavykin commented on app/models/authors_book.rb
> +class AuthorsBook < ApplicationRecord
`AuthorBook`

2019-11-11 10:53 UTC, dmbavykin commented on app/decorators/book_decorator.rb
> +    object.materials.map(&:name).join(', ')
do u use it somewhere else?

with `map` u load in memory materials and then iterate through collection. Instead of this u may use `pluck` method for getting only needed data
`object.materials.pluck(:name).join(', ')`

2019-11-11 10:53 UTC, dmbavykin commented on app/controllers/pages_controller.rb
> +    @best_sellers = Book.includes(:authors).limit(4).decorate
it`s looks like not best sellers

2019-11-11 10:53 UTC, dmbavykin commented on app/controllers/pages_controller.rb
> +    @latest_books = Book.includes(:authors).limit(3).decorate
r use sure that they are latest books?

2019-11-11 10:53 UTC, dmbavykin commented on app/assets/stylesheets/books.scss
> +  cursor: pointer;
u may create helper class `.cursor-pointer` and use it whenever u need in HTML

2019-11-11 10:53 UTC, dmbavykin commented on app/controllers/books_controller.rb
> +    # binding.pry
?

2019-11-11 10:53 UTC, dmbavykin commented on app/controllers/books_controller.rb
> +    @pagy, @books = pagy(BookQuery.call(params))
where is strong params?

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/book_filter_query.rb
> +  def should_filter?
question mark method should only return boolean value

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/book_sort_query.rb
> +    @relation.order(Arel.sql('"books"."created_at" DESC'))
why u used `Arel` here?

2019-11-11 10:53 UTC, dmbavykin commented on app/queries/category_count_query.rb
> +    Category.includes(:books).group(:name).count(:books)
Good idea to separate it. Use `joins` instead of `includes`. Also u may join not full relation `:books`, but just intermediate table

2019-11-11 10:53 UTC, dmbavykin commented on app/views/application/_footer.html.haml
> +            = link_to t('pages.shop'), books_path(category: params[:category], sort: params[:sort] || 'newest'), class: '.nav-link'
move `"newest"` to some helper helper like `default_sort`

2019-11-11 10:53 UTC, dmbavykin commented on app/views/application/_header.html.haml
> +              - @categories.map do |category|
why `.map`? what is wrong with `.each` ?

2019-11-11 10:53 UTC, dmbavykin commented on app/views/books/_books.html.haml
> +          = image_tag '1.jpg', class: 'img-shadow general-thumbnail-img', alt: 'design-book'
why `1.jpg` ?

2019-11-11 10:53 UTC, dmbavykin commented on app/views/books/_categories.html.haml
> +    = link_to books_path(category: nil, sort: params[:sort] || 'newest'), class: 'filter-link' do
the same with `"newest"`
u used it many times

2019-11-11 10:53 UTC, 6aBblKuH commented on app/views/books/show.html.haml
> +          = image_tag '1.jpg', alt: '', class: 'img-responsive'
what is `1.jpg` ?

2019-11-11 10:53 UTC, 6aBblKuH commented on app/views/books/show.html.haml
> +  .mb-80
looks like just static view
we should add it as a feature or just remove until time has come

2019-11-11 10:53 UTC, 6aBblKuH commented on app/views/pages/_best_sellers.html.haml
> +            = image_tag '1.jpg', class: 'img-shadow general-thumbnail-img', alt: 'design-book'
did u add book images ?

2019-11-11 10:53 UTC, 6aBblKuH commented on config/application.rb
> +    config.log_level = :debug
why u defined it? Had u some trouble with production?

2019-11-11 10:53 UTC, 6aBblKuH commented on config/environments/development.rb
> +  Bullet.enable = true
u already defined it in `config/initializers/bullet.rb`

2019-11-11 10:53 UTC, 6aBblKuH commented on db/migrate/20191005165756_create_books.rb
> +      t.string :image
why it is a string field?

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/controllers/books_controller_spec.rb
> +    create_list(:book, 5)
why do we need so many records?

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/controllers/books_controller_spec.rb
> +    create_list(:book, 5)
and we should separate our prepared data for cases depended on them

`show` action can work without 5 created records

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/controllers/books_controller_spec.rb
> +  describe '#show' do
check this with some nonexistent book for `not found` response

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/factories/books.rb
> +    category { Category.limit(1).order(Arel.sql('RANDOM()')).first }
don`t define relation like this

here should be only `category`
we should define all needed data in specs

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/factories/categories.rb
> +    trait :test_unit do
weird trait
do we rly need it?
sound like we should add some other trait for feature specs then

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/features/book_page_spec.rb
> +  let(:book) { Book.first.decorate }
`let(:book) { create(:book)  }`
u should not do it in two waves - create and then select it from db

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/features/catalog_page_spec.rb
> +    create_list(:book, 20)
why do u create so many records?

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/features/catalog_page_spec.rb
> +    Category.all.each do |category|
don`t make real db requests
u should define needed categories in `let` variable and then use it

2019-11-11 10:53 UTC, 6aBblKuH commented on spec/support/database_cleaner.rb
> +require 'database_cleaner'
👍 
nice decision to move it here

2019-11-11 10:59 UTC, 6aBblKuH commented
I left some comments here but sometimes don`t repeat them. Look by yourself for same issues in ur PR, please. As summary, some checkpoints for u:
- YAGNI, don`t provide any functionality what u don`t need for now
- Overhead with randomizing in tests. U should create u test setup directly in test case. All data what will be used in test should be defined in `let` variables
- using `joins` instead of `includes`. Here some good article for clarifying [how it works](https://blog.bigbinary.com/2013/07/01/preload-vs-eager-load-vs-joins-vs-includes.html)

2019-11-11 13:10 UTC, olehvolynets commented on app/controllers/pages_controller.rb
> +    @best_sellers = Book.includes(:authors).limit(4).decorate
best sellers not implemented yet

2019-11-11 13:15 UTC, olehvolynets commented on app/queries/book_filter_query.rb
> +  def should_filter?
It does, guard clause will return nil, that is falsy value, otherwise a string will be returned, that is truthy

2019-11-11 13:16 UTC, olehvolynets commented on app/queries/book_sort_query.rb
> +    @relation.order(Arel.sql('"books"."created_at" DESC'))
rubocop forced to use it

2019-11-11 13:18 UTC, olehvolynets commented on app/views/application/_header.html.haml
> +              - @categories.map do |category|
cause it's returning a list to be rendered

2019-11-11 13:18 UTC, olehvolynets commented on app/views/books/_books.html.haml
> +          = image_tag '1.jpg', class: 'img-shadow general-thumbnail-img', alt: 'design-book'
short

2019-11-11 13:27 UTC, 6aBblKuH commented on app/queries/book_filter_query.rb
> +  def should_filter?
it should be strongly boolean value

keep here only `@params[:category] == 'All'` for providing expected from question mark method behaviour, at first.
Second, u don`t use returned value in caller

2019-11-11 13:27 UTC, 6aBblKuH commented on app/views/application/_header.html.haml
> +              - @categories.map do |category|
`.map` uses for substitution existing elements. Do u rly need to substitute existing elements in categories collection for some parts of view? For such iterations u may use just `.each`

2019-11-11 19:34 UTC, olehvolynets commented on spec/factories/books.rb
> +    category { Category.limit(1).order(Arel.sql('RANDOM()')).first }
it's done to distribute books through categories

2019-11-12 10:32 UTC, 6aBblKuH commented on spec/factories/books.rb
> +    category { Category.limit(1).order(Arel.sql('RANDOM()')).first }
whenever u need specify book category - just do it
```ruby
let(:category) { create(:category) }
let(:book) { create(:book, category: category) }
```

2019-11-21 10:27 UTC, dmbavykin requested changes

2019-11-21 10:27 UTC, dmbavykin commented on app/controllers/pages_controller.rb
> +    @latest_books = Book.includes(:authors).limit(3).decorate
use scope here, please
something like
`scope :newest_first, -> { order(created_at: :desc) }`

2019-11-21 10:27 UTC, dmbavykin commented on spec/factories/categories.rb
> +    sequence(:name) { FFaker::Lorem.unique.word }
👍

2019-11-21 10:27 UTC, dmbavykin commented on spec/features/book_page_spec.rb
> +describe 'Book page', type: :feature do
make it as one `it`

2019-11-21 10:27 UTC, dmbavykin commented on spec/features/catalog_page_spec.rb
> +      create_list(:book, 13)
`Pagy::VARS[:items]`
lets change this value to 2 in tests only

2019-11-21 10:27 UTC, 6aBblKuH commented on spec/queries/category_count_query_spec.rb
> +describe CategoryCountQuery do
here might be dragons

```
                \||/
                |  @___oo
      /\  /\   / (__,,,,|
     ) /^\) ^\/ _)
     )   /^\/   _)
     )   _ /  / _)
 /\  )/\/ ||  | )_)
<  >      |(,,) )__)
 ||      /    \)___)\
 | \____(      )___) )___
  \______(_______;;; __;;;
```

2019-11-21 10:27 UTC, 6aBblKuH commented on spec/queries/category_count_query_spec.rb
> +describe CategoryCountQuery do
u should provide test data and make some `let` with expected result

u should select any records from db

2019-11-21 10:35 UTC, dmbavykin requested changes

2019-11-21 10:35 UTC, 6aBblKuH commented on spec/models/book_spec.rb
> +describe Book, type: :model do
https://relishapp.com/rspec/rspec-rails/docs/directory-structure

u may define this rule in ur rspec config and then no need to add `type` for every spec file. Such metadata will be auto added by file locations if u stay use default locations like `spec/models`

2019-11-29 19:39 UTC, dmbavykin approved these changes

2019-11-29 19:47 UTC, merged