Feature/user authentication
olehvolynets/bookstore pull request #5
Opened 2019-11-29 19:29 UTC by olehvolynets

2019-12-05 17:01 UTC, dmbavykin requested changes

2019-12-05 17:01 UTC, dmbavykin commented on config/locales/devise.security_extension.ja.yml
> +ja:
👍

2019-12-05 17:01 UTC, dmbavykin commented on app/controllers/books_controller.rb
> +    # @categories = Category.all
😨 ?

2019-12-05 17:01 UTC, dmbavykin commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    session['devise.facebook_data'] = request.env['omniauth.auth']
why r u store it in session?

2019-12-05 17:01 UTC, dmbavykin commented on app/models/user.rb
> +  validates :email, uniqueness: true
move it higher than method definition

2019-12-05 17:01 UTC, dmbavykin commented on config/initializers/devise.rb
> +  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
r u think that ur mailer works correctly? :)

2019-12-05 17:01 UTC, dmbavykin commented on spec/features/authentication/sign_in_spec.rb
> +describe 'Sign In', type: :feature do
It`s unnecessary to define type of spec with [this](https://relishapp.com/rspec/rspec-rails/docs/directory-structure) configuration

2019-12-05 17:01 UTC, 6aBblKuH commented on spec/queries/book_sort_query_spec.rb
> +  let(:book_a) { create(:book, title: 'a', price: 1, created_at: 3.days.ago) }
👍

2019-12-05 17:01 UTC, 6aBblKuH commented on spec/support/capybara.rb
> +Capybara.configure do |config|
https://thoughtbot.com/blog/headless-feature-specs-with-chrome
can u try to use headless chrome instead?

2019-12-15 08:58 UTC, dmbavykin requested changes

2019-12-15 08:58 UTC, 6aBblKuH commented on .circleci/config.yml
> +      - run:
<img width="659" alt="Screenshot 2019-12-15 at 10 50 42" src="https://user-images.githubusercontent.com/17334111/70860299-c9062f00-1f28-11ea-8606-9fb65d1fc737.png">
what about other linters? 🤔

2020-01-16 12:59 UTC, Svatok reviewed
http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/

> For new Rails apps: we don't recommend adding the rails-controller-testing gem to your application. The official recommendation of the Rails team and the RSpec core team is to write request specs instead. Request specs allow you to focus on a single controller action, but unlike controller tests involve the router, the middleware stack, and both rack requests and responses. This adds realism to the test that you are writing, and helps avoid many of the issues that are common in controller specs. In Rails 5, request specs are significantly faster than either request or controller specs were in rails 4, thanks to the work by Eileen Uchitelle1 of the Rails Committer Team.

2020-01-16 12:59 UTC, Svatok commented on app/mailers/application_mailer.rb
> +  default from: 'no-reply@bookstore-rg-ov.herokuapp.com'
Move to constant

2020-01-16 12:59 UTC, Svatok commented on config/environments/development.rb
> +  config.action_mailer.smtp_settings = {
remove this

2020-01-16 12:59 UTC, Svatok commented on config/environments/production.rb
> +  config.action_mailer.default_url_options = { host: 'bookstore-rg-ov.herokuapp.com' }
to constant

2020-01-16 12:59 UTC, Svatok commented on spec/features/authentication/sign_up_spec.rb
> +      expect(page).to have_content I18n.t('user_actions.sign_out')
Add tests with email opening - check email body. gem 'capybara-email'

2020-01-16 12:59 UTC, Svatok commented on spec/features/book_page_spec.rb
> +  let!(:book) { create(:book, authors: [create(:author)]).decorate }
Add trait to book factory with name `:with_authors`

2020-01-16 15:26 UTC, Svatok approved these changes

2020-01-16 15:30 UTC, merged